### ISSUE TITLE
Runtime error with h5py package

### ISSUE THREAD

**Issue by eluczko** [hydroffice/hyo_bag#2]
I received the following runtime  error when I was installing hydroffice.

The h5py package that I downloaded from the Linux Mint package manager I could not see the with_phil module defined under the base.py. I downloaded another h5py package from github 
This  package appears to have with_phil in the base.py file however references it from the _objects file two folders up. Hydroffice does not appear to be referencing any of these. 
In the process of troubleshooting the problem I saw many forums saying that I might be circularly referencing "with_phil"

If it is of any help, the IDE I am using is Spyder (Python 2.7) 

```
>>> runfile('/home/wcwi/Projects/2013_WCWI/wd/python/giumas-hyo_bag-76a8293481e3/examples/run_bag_elevation.py', wdir=r'/home/wcwi/Projects/2013_WCWI/wd/python/giumas-hyo_bag-76a8293481e3/examples')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/wcwi/Projects/2013_WCWI/wd/python/giumas-hyo_bag-76a8293481e3/examples/run_bag_elevation.py", line 10, in <module>
    from hydroffice.bag import helper
  File "/usr/lib/python2.7/hydroffice/bag/__init__.py", line 13, in <module>
    from .base import is_bag
  File "/usr/lib/python2.7/hydroffice/bag/base.py", line 12, in <module>
    from h5py._hl.base import with_phil
ImportError: cannot import name with_phil
```

**Comment by eluczko** [comment]
My issue was mostly caused by my inexperience in the python environment than anything else. 
I was able to solve my problem in two ways.

1) After reinstalling a new package that may have been giving me previous runtime errors (ie. cython, or h5py), I closed and restarted spyder. Once I restarted the program the new packages were being properly referenced.

2) I also had to do some digging online to see how I could change my path in my environment and make sure that all the supporting libraries were being properly referenced in my IDE.

The following commands were very helpful (once again, this will probably only be helpful to those new to python like me).
import sys

```
#     prints system path directories on a new line
print '\n'.join(sys.path) 
 #     appends a new path to the system path                                                
sys.path.append('\directory\you\wish\to\append')
#     removes a path from the system path     
sys.path.remove('\directory\you\wish\to\remove')       
  #     prints out which names a module defines. 
print '\n'.join(dir(modulename))                                 
```

After I had my libraries sorted out and properly referenced, I no longer had any trouble with my hydroffice installation. The instructions here (http://www.hydroffice.org/posts/bag-library-linux-mint/) also worked!
